version: '3.3'
services:
   api:
     build:
      context: ./api
      dockerfile: Dockerfile
      args:
        buildno: 1
     ports:
       - "5000:8000"
     restart: always
     environment:
       TEST: test